### ISSUE TITLE
Sending "," in subprotocols even if there is only one string.

### ISSUE THREAD

**Issue by jan-pintr** [crossbario/autobahn-android#12]
Hello I've been trying to implement WebSocket client side which needed to send string "text-stream" as sub-protocol in handshake key. But WebSocketWriter send "text-stream," So I suggest to add in the method sendClientHandshake()

if (i != message.mSubprotocols.length - 1) {
      mBuffer.write(", ");
}

to add comma only for separate strings.

**Comment by oberstet** [comment]
this has been merged long ago: https://github.com/crossbario/autobahn-android/blob/master/Autobahn/src/de/tavendo/autobahn/WebSocketWriter.java#L176
