### ISSUE TITLE
Wrong WampOptions default parameter.

### ISSUE THREAD

**Issue by danielfaust** [crossbario/autobahn-android#23]
mReceiveTextMessageRaw should get set to true in the constructor.

See https://groups.google.com/forum/?fromgroups=#!topic/autobahnws/W97TBS84HIw

**Comment by oberstet** [comment]
yeah, bug. won't fix though, because we'll move to WAMPv2 anyway .. pls see: https://github.com/crossbario/autobahn-android/issues/92
