### ISSUE TITLE
Automatic reestablishment of prefixes and subscriptions upon reconnect

### ISSUE THREAD

**Issue by danielfaust** [crossbario/autobahn-android#24]
I was just testing the automatic reconnection feature, but there seems to be an issue of using it together with a WampConnection.prefix call in the WampConnection.onOpen override.

```java
m_acAutobahn.connect(...uri..., new Wamp.ConnectionHandler() {
  @Override
   public void onOpen() {
     m_acAutobahn.prefix("rpc", "http://example.com/main/rpc#");
     m_acAutobahn.call("rpc:call", Object.class, new Wamp.CallHandler() {
     }, ...ojbect...);
```
The code above causes a generic error response to the call (invalid WAMP message: missing array close or invalid additional args)

The code below works just fine upon an automatic reconnection
```java
m_acAutobahn.connect(...uri..., new Wamp.ConnectionHandler() {
  @Override
   public void onOpen() {
     m_acAutobahn.call("http://example.com/main/rpc#call", Object.class, new Wamp.CallHandler() {
     }, ...ojbect...);
```

**Comment by oberstet** [comment]
"prefixes" are no longer part of WAMPv2
