### ISSUE TITLE
Multiple Endpoints on a Single Connection

### ISSUE THREAD

**Issue by falvojr** [crossbario/autobahn-android#70]
First, congratulations for the project! It's a fantastic initiative! 
I would like to ask you some questions about it: 

1. Is there a way to create a single WebSocket connection and send messages to multiple endpoints on the server? I saw that there are examples of this using RPC, but I would only use WebSocket. I would like something like SocksJs with STOMP:

    `var ws = new SockJS(url);`
    `var client = Stomp.over(ws);`
    `client.connect(headers, connectCallback);`
    `client.send("/queue/test", {priority: 9}, "Hello, STOMP");`

2. The WSS protocol is fully supported by Android Autobahn?

3. Is there any particular reason for using the Jackson 1.X? It's what I use version 2.x and I'm thinking of changing my fork of the autobahn for this version.

Already, thanks!

**Comment by oberstet** [comment]
1. A WS connection is always to a single URL (rgd WS opening handshake). What you do on that connection is your thing.
2. No. This will be addressed now as part of https://github.com/crossbario/autobahn-android/issues/92
3. See https://github.com/crossbario/autobahn-android/issues/45
