### ISSUE TITLE
WebSocketConnectionObserver not found

### ISSUE THREAD

**Issue by KashaMalaga** [crossbario/autobahn-android#76]
In last version could find this class, and couldnt find any info if it was removed :(

**Comment by oberstet** [comment]
I don't recall we ever had such a class .. sorry

**Comment by PingForward** [comment]
@oberstet @KashaMalaga 
It seems Webrtc uses your library to establish socket connection.
Here is the file that have dependencies on the autobahn lib [WebSocketChannelClient.java](https://chromium.googlesource.com/external/webrtc/+/6f6ef72950b9bda79392e83d7b1495d4ff07b4a2/talk/examples/android/src/org/appspot/apprtc/WebSocketChannelClient.java)

In the autobahn v0.5.2 I missed some imports too (I get the lib from gradle `compile 'com.github.tavendo:AutobahnAndroid:v0.5.2'`)
`import de.tavendo.autobahn.WebSocket.WebSocketConnectionObserver;`

And some methods have different implementation.

Any suggestions? Could you check this file?

**Comment by oberstet** [comment]
I wasn't aware of that use of AutobahnAndroid. Interesting. I don't have time to look into this though - but we've been talking to a contract developer lately, and maybe we (Tavendo/Crossbar.io) will sponsor reviving development of this. If so, then we'll address it. Hence, reopening ..

**Comment by PingForward** [comment]
It seems they used a very old build. 
There is note.txt and it contains

> AutobahnAndroid
> Copyright 2011,2012 Tavendo GmbH. Licensed under Apache 2.0
> This product includes software developed at Tavendo GmbH http://www.tavendo.de

**Comment by oberstet** [comment]
Well, no clue. As said, the class you are missing isn't in Autobahn - maybe Google added it to their fork. Dunno. Please ask Google.

**Comment by PhilLab** [comment]
@PingForward Try to use ``WebSocket.ConnectionHandler``

**Comment by j796160836** [comment]
I think that google use the version 1 of the autobahn wrapped into jar and into its repository.
https://github.com/crossbario/autobahn-java/tree/version-1
Just use that jar will be ok. (Just some legacy code.)
