### ISSUE TITLE
Getting sessionId

### ISSUE THREAD

**Issue by BackPackerDz** [crossbario/autobahn-android#80]
Hi, please how can I get the sessionID ?

**Comment by pl-repo** [comment]
Any update on above question. does exclude/elidgible work in current Android implementation?

**Comment by BackPackerDz** [comment]
You have to do it by yourself !

**Comment by oberstet** [comment]
we need to move this library to WAMP v2 .. pls see https://github.com/crossbario/autobahn-android/issues/92

as part of that, a proper WAMP session details object will be available, that holds the WAMP session ID.

I am closing this one .. we wont touch the old WAMPv1 codebase anyway
