### ISSUE TITLE
Realm

### ISSUE THREAD

**Issue by klanjabrik** [crossbario/autobahn-android#87]
Why there is no "realm" configuration?

**Comment by Desnoo** [comment]
No quite sure, but I think Wamp v1 does not support this kind.

**Comment by goeddea** [comment]
Autobahn-Android only supports WAMP v1, which is quite different from v2. 

If you are looking for a WAMP v2 Android client, then AFAIK jawampa is your best bet, which https://github.com/Vinelab/Android-wamp-client wraps/adapts.
