### ISSUE TITLE
Status: 400 (This server only speaks WebSocket subprotocols wamp.2.msgpack.batched, wamp.2.msgpack, wamp.2.json.batched, wamp.2.json)

### ISSUE THREAD

**Issue by firasalkafri** [crossbario/autobahn-android#88]
While trying to connect to Crossbar from Android using the up to date source code

**Comment by oberstet** [comment]
yes, AutobahnAndroid is still on WAMP1

**Comment by firasalkafri** [comment]
Any updates on the AutobahnAndroid support and development for WAMPv2?
