### ISSUE TITLE
多个手机登录同一个账号（login on 2 client）

### ISSUE THREAD

**Issue by ouyangzn** [crossbario/autobahn-android#90]
0.5.2版本，多个手机登录同一个账号时，onClose收到的code总是3，跟其他掉线情况是一样的，区分不出什么时候是多地登录
version： 0.5.2
when i login on 2 client, i received error code 3, the same as other case(such as network is close). so i don't  kown  the  reason of  webSocket closed.
![_20160203182429](https://cloud.githubusercontent.com/assets/8808376/12779573/8bde42f8-caa3-11e5-9b3d-1838de5a4a7f.png)

**Comment by oberstet** [comment]
haha;) I don't speak chinese

**Comment by ouyangzn** [comment]
@oberstet  you can speak english, my problem is, when i login on 2 phone, i received error, the code is 3, when my network is disable, the error code is 3 too, so i don't know the real reason.
