### ISSUE TITLE
Fatal Exception: java.lang.OutOfMemoryError

### ISSUE THREAD

**Issue by artemkutukov** [crossbario/autobahn-android#91]
dalvik.system.VMRuntime.newNonMovableArray (VMRuntime.java)
java.nio.MemoryBlock.allocate (MemoryBlock.java:125)
java.nio.ByteBuffer.allocateDirect (ByteBuffer.java:72)
de.tavendo.autobahn.WebSocketReader.<init> (WebSocketReader.java:94)
de.tavendo.autobahn.WebSocketConnection.createReader (WebSocketConnection.java:424)
de.tavendo.autobahn.WebSocketConnection$WebSocketConnector.onPostExecute (WebSocketConnection.java:105)
de.tavendo.autobahn.WebSocketConnection$WebSocketConnector.onPostExecute (WebSocketConnection.java:1)
android.os.AsyncTask.finish (AsyncTask.java:632)
android.os.AsyncTask.access$600 (AsyncTask.java:177)
android.os.AsyncTask$InternalHandler.handleMessage (AsyncTask.java:645)
android.os.Handler.dispatchMessage (Handler.java:102)
android.os.Looper.loop (Looper.java:136)
android.app.ActivityThread.main (ActivityThread.java:5584)
java.lang.reflect.Method.invokeNative (Method.java)
java.lang.reflect.Method.invoke (Method.java:515)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1268)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1084)
dalvik.system.NativeStart.main (NativeStart.java)

**Comment by Thomas-Valloo** [comment]
Why was this issue closed ?
