### ISSUE TITLE
wss Secure support for custom TrustStore setSSLSocketFactory

### ISSUE THREAD

**Issue by RoundSparrow** [crossbario/autobahn-android#93]
I see in the early days there was an option getVerifyCertificateAuthority to create a dummy trust store, but that seems removed.

Is there any way to specify a custom trust store? Nearly identical to the example Google provides for http connections?

http://developer.android.com/intl/pt-br/training/articles/security-ssl.html

Function equal to:

    HttpsURLConnection urlConnection =
    (HttpsURLConnection)url.openConnection();
    urlConnection.setSSLSocketFactory(context.getSocketFactory());

Thank you.

**Comment by oberstet** [comment]
this isn't a Autobahn issue

**Comment by RoundSparrow** [comment]
What does that mean? wss means "WebSocket Secure", is that now what Autobahn does? The getVerifyCertificateAuthority option I referenced is from your own source tree: https://github.com/crossbario/autobahn-android/pull/14/files/06caa3c0e6f8aa004d1e91588ea71a5843e576ee?diff=unified

**Comment by oberstet** [comment]
it's not an Autobahn issue, because what you link above isn't in the library, but in an unmerged PR - that won't get merged.

wss support will be added as part of https://github.com/crossbario/autobahn-android/issues/92

sorry for my swift responses .. no offense .. I am just ultra short in time

**Comment by RoundSparrow** [comment]
Thank you for the additional detail. FYI: Google (Chrome team) seems to be using wss in the AppRTC demo Android app for WebRTC - which is where I ran into the need for self-signed SSL certificate support. Have a good week.

**Comment by oberstet** [comment]
@RoundSparrow I need to get into this again .. maybe things with TLS on Android (maybe even when combined with NIO) have improved. Have a nice week too!

**Comment by RoundSparrow** [comment]
For sake of others who come along here... The open source example App for WebRTC i referenced is here: https://chromium.googlesource.com/external/webrtc/+/master/webrtc/examples/androidapp/src/org/appspot/apprtc/WebSocketChannelClient.java
