### ISSUE TITLE
Installing autobahn-androir in Android Studio

### ISSUE THREAD

**Issue by davidrojo** [crossbario/autobahn-android#97]
Hello,

I am trying to use this library in a project but I am unable to compile it.

I've added to my app gradle the next requirements:

```
dependencies {
    ....
    compile 'com.github.crossbario:autobahn-android:v0.5.2'
    compile files('libs/autobahn-0.5.0.jar')
}
```

And added to the project gradle the `maven { url "https://jitpack.io" }` requirement.

When I run the project I receive the next error:

```
Error:Execution failed for task ':app:transformResourcesWithMergeJavaResForDebug'.
> com.android.build.api.transform.TransformException: com.android.builder.packaging.DuplicateFileException: Duplicate files copied in APK META-INF/ASL2.0
	File1: C:\Users\David\.gradle\caches\modules-2\files-2.1\org.codehaus.jackson\jackson-core-asl\1.9.7\2dd41e7570f5c73e63a6a1311671a60c817e1989\jackson-core-asl-1.9.7.jar
	File2: C:\Users\David\.gradle\caches\modules-2\files-2.1\org.codehaus.jackson\jackson-mapper-asl\1.9.7\3bc2efad5ceb9e24e44f731d4282b5df3ea6d23f\jackson-mapper-asl-1.9.7.jar

```
Any help?

**Comment by davidrojo** [comment]
Ok, I finally got it working. There should be a better documentation on how to use it as the getting started documentation in the website is not correct.

Finally removed all jars (are not necessary) and added the jitpack gradle dependency `compile 'com.github.crossbario:autobahn-android:v0.5.2'` and added in the androidi section of the app gradle the following:

```
packagingOptions {
    exclude 'META-INF/INDEX.LIST'
    exclude "META-INF/ASL2.0"
}
```

**Comment by raizal** [comment]
I got this error too. But, instead doing what you suggest, I exclude the jackson on autobahn and it works

> compile ('com.github.crossbario:autobahn-android:v0.5.2'){
        exclude group: 'org.codehaus.jackson', module:'jackson-mapper-asl'
    }

**Comment by kondalaraot** [comment]
How to upgrade to latest version ,Is this building from  crossbario/autobahn-java github repo?
